### PR TITLE
[G2M] plotly-bar - add horizontal mode for bar

### PR DESCRIPTION
**Pull request by kc-leung**
Screen Shot 2022-07-12 at 9 59 37 AM
Screen Shot 2022-07-12 at 9 59 31 AM

### CODE REVIEW

**Review by woozyking — APPROVED** [review]
It would be great if there are some screenshots and maybe direct Storybook links (such as https://60f5a69eddb5b90039b6d17c-ciroggdsnn.chromatic.com/?path=/story/plotly-bar--horizontal) to help members with the review, something like https://github.com/EQWorks/react-maps/pull/136

**Comment by geoerika** [comment]
> It would be great if there are some screenshots and maybe direct Storybook links (such as https://60f5a69eddb5b90039b6d17c-ciroggdsnn.chromatic.com/?path=/story/plotly-bar--horizontal) to help members with the review, something like [EQWorks/react-maps#136](https://github.com/EQWorks/react-maps/pull/136)

Same here! Always provide a short description of changes, screenshot/recording & storybook link, to make the reviewer's work easier & to save our time.

**Review by geoerika — APPROVED** [review]

**Comment by geoerika** [comment]
Not sure it's possible, the labels on the y-Axis are very close to the chart. Could you please look into adding a bit of space between the labels & the y-axis?

**Comment by kc-leung** [comment]
@geoerika I will change the version to 0.7.1 is it ok?

**Pull request merged**
