### PR TITLE
[G2M] Plotly - add dynamic formatting option

### LINKED ISSUE #179: Plotly charts - add formatting function to data values
**Problem:**

- Plotly charts don't have a prop for data value formatting

**Solution:**

- add data formatting prop & adjust code to display values in tooltip & on the charts

### PR DESCRIPTION
**Pull request by kc-leung**
fixes #179 

- Added data text formatting display option
- Added xAxis and yAxis label prefix & suffix option

### CODE REVIEW

**Review by geoerika — CHANGES_REQUESTED** [review]
@kc-leung Please create a storybook for a horizontal bar-chart which you pass a formatting function prop with rounding and adding a `% `suffix to values:
```
   {
            "dealer_id": 1,
            "resolution": 1000,
            "pop": 21180,
            "pop_male": 32.40863787375415,
            "pop_female": 67.59136212624584,
            "hh_income_0_50k": 18.209803457257873,
            "hh_income_50_100k": 25.50319677954061,
            "hh_income_100_150k": 44.54179493251243,
            "hh_income_150_200k": 7.009235140895099,
            "hh_income_200k+": 4.735969689793985,
            "avg_hh_income": 46210,
            "highest_education_no_education": 16.616879685007827,
            "highest_education_secondary_education": 33.73102928425884,
            "highest_education_apprenticeship_trades": 7.902637711138798,
            "highest_education_college_uni_below_bachelor": 25.956706030345078,
            "highest_education_uni_bachelor": 15.329826955841316,
            "highest_education_uni_advanced": 0.46292033340814015
        },
```

It should look something like this, of course, before applying the formatting:
Screen Shot 2022-09-12 at 3 51 24 PM

**Comment by kc-leung** [comment]
> @kc-leung Please create a storybook for a horizontal bar-chart which you pass a formatting function prop with rounding and adding a `% `suffix to values:
> 
> ```
>    {
>             "dealer_id": 1,
>             "hh_income_0_50k": 18.209803457257873,
>             "hh_income_50_100k": 25.50319677954061,
>             "hh_income_100_150k": 44.54179493251243,
>             "hh_income_150_200k": 7.009235140895099,
>             "hh_income_200k+": 4.735969689793985,
>         },
> ```
> 
> It should look something like this, of course, before applying the formatting: Screen Shot 2022-09-12 at 3 51 24 PM

@geoerika  Added
image

**Comment by geoerika** [comment]
@kc-leung Do you know why the longest bar label in the chart gets cut off in the right? Especially when you shrink the char container?
It's not very urgent if you have no idea at the moment, we can fix it next week.
Screen Shot 2022-09-13 at 11 43 56 AM

**Comment by kc-leung** [comment]
> @kc-leung Do you know why the longest bar label in the chart gets cut off on the right side? Especially when you shrink the char container? It's not very urgent if you have no idea at the moment, we can fix it next week. Screen Shot 2022-09-13 at 11 43 56 AM

I don't really know I will need time to figure it out. Probably from resize-detector

**Comment by geoerika** [comment]
> > @kc-leung Do you know why the longest bar label in the chart gets cut off on the right side? Especially when you shrink the char container? It's not very urgent if you have no idea at the moment, we can fix it next week.
> 
> I don't really know I will need time to figure it out. Probably from resize-detector

Ok, then let's leave it for the next week.

**Review by geoerika — APPROVED** [review]

**Review by woozyking — APPROVED** [review]

**Pull request merged**
