### PR TITLE
[G2M] Plotly - 2 trend line/double line chart

### LINKED ISSUE #200: Double trend line chart
Screen Shot 2022-10-07 at 1 02 40 PM

### PR DESCRIPTION
**Pull request by kc-leung**
fixes #200 

- Added plotly double line chart component

Screen Shot 2022-10-20 at 3 19 57 PM

### CODE REVIEW

**Review by geoerika — APPROVED** [review]

**Review by woozyking — APPROVED** [review]
agree that 0.9 makes more sense

**Review by Hamaad102 — APPROVED** [review]
Looks good. Only comment I have (and it's overly nitpicky) is it possible to add dots on points similar to the line graph? I think for accessibilities sake it might be a good thing. Just as an example the green line in the image below is showing three plot points but it just blends together. Aside from that it looks good!

Screenshot 2022-10-24 105803

**Comment by kc-leung** [comment]
> Looks good. Only comment I have (and it's overly nitpicky) is it possible to add dots on points similar to the line graph? I think for accessibilities sake it might be a good thing. Just as an example the green line in the image below is showing three plot points but it just blends together. Aside from that it looks good!
> 
> Screenshot 2022-10-24 105803

yea it is possible. I actually removed it cuz there was not dots in the design @vlatawiec

**Review by vlatawiec — APPROVED** [review]
As @Hamaad102 said, dots would improve accessibility! It wasn't included since I wasn't sure it could be implemented (and since other line graphs were not using individual data points) but if possible, @kc-leung adding dots for individual points would be awesome! I'll update the design to reflect that asasp

**Pull request merged**
