### PR TITLE
[G2M] Plotly/group by value

### PR DESCRIPTION
**Pull request by vxsl**
# dependency for EQWorks/widget-studio#51
### [(^ contains recordings of all these features being used)](https://github.com/EQWorks/widget-studio/pull/51)
---

the commit history is messy on this one, apologies. This PR is larger than I would like it to be.

Lots of general refactoring among the changes outlined below - the idea is to make the plotly implementation as generic as possible, potentially making it easier to add other chart types down the line.

`commit-watch` is choking, please ignore the big red :x: 

---

- grouping by value introduced to all plotly components
  - `useTransformedData` custom hook has been introduced to allow each component to take advantage of this
  -  [here is a video of it in action in `widget-studio`](https://user-images.githubusercontent.com/53827672/150412660-a4ca016c-ed9c-4acc-bbcc-29530471479c.mp4)

- added `baseColor` to plotly components
  - the actual generation of the color schemes leaves a lot to be improved, but should be easy to change going forward, now that the structure is in place.

- new dependencies
  - `color-convert` for current color scheme generation implementation
  - `iwanthue` for current color scheme generation implementation
  - `lodash.merge` for deep-merging objects

- fully adopt `goober` in plotly components

- plotly components flow has been simplified
  - before: `Bar -> ResponsivePlot -> PlotlyWrapper`
  - now: `Bar -> CustomPlot`

- plotly components now handle subplots instead of leaving it up to `plotly.js`
  - i.e. an independent `Plot` is rendered for each subplot
  - allows for easier styling in the document flow

- plotly components now render a title for each subplot, independent of `plotly.js`
  - position can be controlled to 6 points of the visualization via `titlePosition` prop

- plotly components now handle the legend instead of leaving it up to `plotly.js`
  - position can be set to 4 corners of the visualization via `legendPosition` prop
  - more extensible, i.e. we can start to introduce custom styling to the legend
  - now, for example, 4 subplots !== 4 legends :)
  
- various styling issues fixed in plotly components
  - `automargin` plotly flag is awesome <3
  - was able to avoid some previous script-based styling, consequently was able to remove dependency `react-resize-detector` 

---
### Note

if you encounter something like this where there's a long distance from the title to the chart, note that it is a `plotly.js` limitation. Currently trying to work around it but didn't want to get stuck on it in the meantime.
image

### CODE REVIEW

**Review by geoerika — APPROVED** [review]
Changes look fine. The only thing I would like @sallkall @YizhiCatherineZhang to have a say are the colours resulting in the charts. While keeping the shades closer in values to each other gives a relatively pleasing view at the first look (with exceptions, lol), I feel like for example, having 3 shades of green and 3 shades of blue will make data harder to distinguish. This is just a personal opinion, again, Sally & Catherine should know better and would like to hear their opinions on this.

**Comment by geoerika** [comment]
Also, there is a commit-watch error to fix.

**Comment by vxsl** [comment]
> Changes look fine. The only thing I would like @sallkall @YizhiCatherineZhang to have a say are the colours resulting in the charts. While keeping the shades closer in values to each other gives a relatively pleasing view at the first look (with exceptions, lol), I feel like for example, having 3 shades of green and 3 shades of blue will make data harder to distinguish. This is just a personal opinion, again, Sally & Catherine should know better and would like to hear their opinions on this.

Yeah, 100% agree.

> Also, there is a commit-watch error to fix.

Yep I mentioned this in the PR description as well. For some reason I can't resolve it. It's not an "actual" error about a commit message but rather a failure to run. Been happening to me a lot lately for some reason...

**Comment by geoerika** [comment]
> > Also, there is a commit-watch error to fix.
> 
> Yep I mentioned this in the PR description as well. For some reason I can't resolve it. It's not an "actual" error about a commit message but rather a failure to run. Been happening to me a lot lately for some reason...

I am no expert in this, but I remember having errors with `commit-watch` and Leo instructed me to change the fetch-depth to 0.
        ` fetch-depth: ${{ env.fetch_depth }}`
https://github.com/EQWorks/chart-system/blob/8e5e80b17ca664d4d0b0f57b8d4ba82182fcf2ce/.github/workflows/master.yml#L52

**Comment by vxsl** [comment]
> I am no expert in this, but I remember having errors with commit-watch and Leo instructed me to change the fetch-depth to 0.
fetch-depth: ${{ env.fetch_depth }}

That worked :D thanks

**Review by sallkall — APPROVED** [review]

**Pull request merged**
