### PR TITLE
[WIP] Add Pyramid chart for plotly

### PR DESCRIPTION
**Pull request by kc-leung**
- Added Pyramid-bar chart type for plotly

### CODE REVIEW

**Comment by kc-leung** [comment]
@woozyking I think I accidentally pushed the changes into master branch before branching off into a new branch for this PR how can I fix it?

**Comment by woozyking** [comment]
> @woozyking I think I accidentally pushed the changes into master branch before branching off into a new branch for this PR how can I fix it? 

git reset to its previous state in master

**Comment by kc-leung** [comment]
> > @woozyking I think I accidentally pushed the changes into master branch before branching off into a new branch for this PR how can I fix it?
> 
> git reset to its previous state in master

I can't git push --force after resetting tho cuz it is a protected branch

**Comment by woozyking** [comment]
> I can't git push --force after resetting tho cuz it is a protected branch

Can you lemme know which commit to reset on so I can try it?

**Comment by kc-leung** [comment]
> > I can't git push --force after resetting tho cuz it is a protected branch
> 
> Can you lemme know which commit to reset on so I can try it? should it be resetting to [d30b51d](https://github.com/EQWorks/chart-system/commit/d30b51db97f5b3e5957953457bcb8aa15c714a39)?

yes, please these last 2 commits. 
image

**Pull request closed without merging**
